version: '3.9'

services:

  sports-api-db-container:
    image: postgres:14-alpine
    container_name: sports-api-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sports_api_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
